//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace MigrationTest.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitCourseEntityMappings();
			InitStudentEntityMappings();
			InitStudentCourseEntityMappings();
		}

		/// <summary>Inits CourseEntity's mappings</summary>
		private void InitCourseEntityMappings()
		{
			this.AddElementMapping("CourseEntity", @"MigrationTest", @"public", "course", 3, 0);
			this.AddElementFieldMapping("CourseEntity", "Id", "Id", false, "Integer", 0, 10, 0, true, "public.course_Id_seq", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("CourseEntity", "Instructor", "instructor", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("CourseEntity", "Name", "name", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 2);
		}

		/// <summary>Inits StudentEntity's mappings</summary>
		private void InitStudentEntityMappings()
		{
			this.AddElementMapping("StudentEntity", @"MigrationTest", @"public", "student", 4, 0);
			this.AddElementFieldMapping("StudentEntity", "Email", "email", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("StudentEntity", "Grade", "grade", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("StudentEntity", "Id", "Id", false, "Integer", 0, 10, 0, true, "public.student_Id_seq", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("StudentEntity", "Name", "name", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits StudentCourseEntity's mappings</summary>
		private void InitStudentCourseEntityMappings()
		{
			this.AddElementMapping("StudentCourseEntity", @"MigrationTest", @"public", "student_course", 4, 0);
			this.AddElementFieldMapping("StudentCourseEntity", "CourseId", "courseId", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("StudentCourseEntity", "Id", "Id", false, "Integer", 0, 10, 0, true, "public.student_course_Id_seq", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("StudentCourseEntity", "RegistrationDate", "registrationDate", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 2);
			this.AddElementFieldMapping("StudentCourseEntity", "StudentId", "studentId", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 3);
		}

	}
}
