//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace TestTraining.HelperClasses
{
	/// <summary>Field Creation Class for entity StudentEntity</summary>
	public partial class StudentFields
	{
		/// <summary>Creates a new StudentEntity.Email field instance</summary>
		public static EntityField2 Email { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StudentFieldIndex.Email); }}
		/// <summary>Creates a new StudentEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StudentFieldIndex.Id); }}
		/// <summary>Creates a new StudentEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StudentFieldIndex.Name); }}
	}
	

}