//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using LLtest.FactoryClasses;
using LLtest.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace LLtest.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitStudentEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits StudentEntity's info objects</summary>
		private void InitStudentEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(StudentFieldIndex), "StudentEntity");
			this.AddElementFieldInfo("StudentEntity", "Email", typeof(System.String), false, false, false, false,  (int)StudentFieldIndex.Email, 255, 0, 0);
			this.AddElementFieldInfo("StudentEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)StudentFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("StudentEntity", "Name", typeof(System.String), false, false, false, false,  (int)StudentFieldIndex.Name, 255, 0, 0);
		}
	}
}