//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using MigrationTest.FactoryClasses;
using MigrationTest.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace MigrationTest.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitCourseEntityInfo();
			InitStudentEntityInfo();
			InitStudentCourseEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits CourseEntity's info objects</summary>
		private void InitCourseEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CourseFieldIndex), "CourseEntity");
			this.AddElementFieldInfo("CourseEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)CourseFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("CourseEntity", "Instructor", typeof(System.String), false, false, false, false,  (int)CourseFieldIndex.Instructor, 255, 0, 0);
			this.AddElementFieldInfo("CourseEntity", "Name", typeof(System.String), false, false, false, false,  (int)CourseFieldIndex.Name, 255, 0, 0);
		}

		/// <summary>Inits StudentEntity's info objects</summary>
		private void InitStudentEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(StudentFieldIndex), "StudentEntity");
			this.AddElementFieldInfo("StudentEntity", "Email", typeof(System.String), false, false, false, false,  (int)StudentFieldIndex.Email, 255, 0, 0);
			this.AddElementFieldInfo("StudentEntity", "Grade", typeof(System.String), false, false, false, false,  (int)StudentFieldIndex.Grade, 255, 0, 0);
			this.AddElementFieldInfo("StudentEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)StudentFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("StudentEntity", "Name", typeof(System.String), false, false, false, false,  (int)StudentFieldIndex.Name, 255, 0, 0);
		}

		/// <summary>Inits StudentCourseEntity's info objects</summary>
		private void InitStudentCourseEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(StudentCourseFieldIndex), "StudentCourseEntity");
			this.AddElementFieldInfo("StudentCourseEntity", "CourseId", typeof(System.Int32), false, true, false, false,  (int)StudentCourseFieldIndex.CourseId, 0, 0, 10);
			this.AddElementFieldInfo("StudentCourseEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)StudentCourseFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("StudentCourseEntity", "RegistrationDate", typeof(System.DateTime), false, false, false, false,  (int)StudentCourseFieldIndex.RegistrationDate, 0, 0, 0);
			this.AddElementFieldInfo("StudentCourseEntity", "StudentId", typeof(System.Int32), false, true, false, false,  (int)StudentCourseFieldIndex.StudentId, 0, 0, 10);
		}
	}
}